/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = ['.carbonads[_ngcontent-%COMP%] {\n  border: solid rgba(255, 255, 255, 0.5) !important;\n  border-width: 1px 1px !important;\n  background: transparent !important;\n  box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.4);\n  width: 330px !important;\n  height: 120px;\n  padding: 15px !important;\n  margin-left: 120px;\n  margin-bottom: 80px;\n  border-radius: 0px;\n}'];
//# sourceMappingURL=/Users/James/PycharmProjects/jimid-web/src/src/app/user/app-nav/app-nav.component.css.shim.js.map