/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
export var styles = [''];
//# sourceMappingURL=/Users/James/PycharmProjects/jimid-web/src/src/app/user/user.component.css.js.map